/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCollaboratorsRouteImport } from './routes/_app.collaborators'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app.customers.$customerId'
import { Route as AppChatThreadIdRouteImport } from './routes/_app.chat.$threadId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCollaboratorsRoute = AppCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AppAgentsRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRouteWithChildren
  '/collaborators': typeof AppCollaboratorsRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/finance': typeof AppFinanceRoute
  '/products': typeof AppProductsRoute
  '/services': typeof AppServicesRoute
  '/skills': typeof AppSkillsRoute
  '/usage': typeof AppUsageRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AppAgentsRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRouteWithChildren
  '/collaborators': typeof AppCollaboratorsRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/finance': typeof AppFinanceRoute
  '/products': typeof AppProductsRoute
  '/services': typeof AppServicesRoute
  '/skills': typeof AppSkillsRoute
  '/usage': typeof AppUsageRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/collaborators': typeof AppCollaboratorsRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/finance': typeof AppFinanceRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/chat/$threadId': typeof AppChatThreadIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/recover'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/agents'
    | '/calendar'
    | '/chat'
    | '/collaborators'
    | '/customers'
    | '/finance'
    | '/products'
    | '/services'
    | '/skills'
    | '/usage'
    | '/chat/$threadId'
    | '/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/recover'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/agents'
    | '/calendar'
    | '/chat'
    | '/collaborators'
    | '/customers'
    | '/finance'
    | '/products'
    | '/services'
    | '/skills'
    | '/usage'
    | '/chat/$threadId'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/privacy'
    | '/recover'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/_app/agents'
    | '/_app/calendar'
    | '/_app/chat'
    | '/_app/collaborators'
    | '/_app/customers'
    | '/_app/finance'
    | '/_app/products'
    | '/_app/services'
    | '/_app/skills'
    | '/_app/usage'
    | '/_app/chat/$threadId'
    | '/_app/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RecoverRoute: typeof RecoverRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaborators': {
      id: '/_app/collaborators'
      path: '/collaborators'
      fullPath: '/collaborators'
      preLoaderRoute: typeof AppCollaboratorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/chat/$threadId': {
      id: '/_app/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatThreadIdRoute: AppChatThreadIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppCollaboratorsRoute: typeof AppCollaboratorsRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppFinanceRoute: typeof AppFinanceRoute
  AppProductsRoute: typeof AppProductsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppUsageRoute: typeof AppUsageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppCollaboratorsRoute: AppCollaboratorsRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppFinanceRoute: AppFinanceRoute,
  AppProductsRoute: AppProductsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppUsageRoute: AppUsageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RecoverRoute: RecoverRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
